name: "CI(Integração Continua):Primeira Action"

on:
  # ATIVA O FLUXO DE TRABALHO PARA CADA PUSH OU PULL QUE ACONTECER DENTRO DA BRANCH MAIN
  push:
    branches: [ "teste","main" ]
  pull_request:
     types: [opened, syncronize]
    #branches: [ "main" ]
# DEFINIMOS O QUE QUEREMOS EXECUTAR(JOBS)


jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/checkout@v4
        with:
          node-version: 20.x
          cache: 'npm'
          - name: Install Dependencies
          run: npm install
          - name: Run Tests
          run: npm test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm build
